[platformio]
default_envs = main

[env]
platform = espressif32 @ ~6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -Wall
    -DUSER_SETUP_LOADED=1
    -DILI9341_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MISO=19
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=4
    -DTFT_RST=2
    -DTOUCH_CS=15
    -DLOAD_GLCD -DLOAD_FONT2 -DLOAD_FONT4 -DLOAD_FONT6 -DLOAD_FONT7 -DLOAD_FONT8
    -DLOAD_GFXFF -DSMOOTH_FONT
    -DSPI_FREQUENCY=27000000
    -DSPI_READ_FREQUENCY=20000000
    -DSPI_TOUCH_FREQUENCY=2500000

[env:main]
build_src_filter = +<*> -<main_*.cpp>
lib_deps =
    SPI
    Wire
    WiFi
    bodmer/TFT_eSPI
    paulstoffregen/XPT2046_Touchscreen
    adafruit/Adafruit ADS1X15
    links2004/WebSockets@^2.6.1

[env:wifi_test]
build_src_filter = -<*> +<main_wifi_test.cpp>
lib_deps =
    links2004/WebSockets@^2.6.1

[env:display_test]
build_src_filter = -<*> +<main_display_test.cpp>
lib_deps =
    bodmer/TFT_eSPI
    paulstoffregen/XPT2046_Touchscreen

[env:flow_tab_test]
build_src_filter = -<*> +<main_flow_tab_test.cpp>
lib_deps =
    bodmer/TFT_eSPI
    paulstoffregen/XPT2046_Touchscreen
    links2004/WebSockets@^2.6.1
